spring.application.name=mysacco
server.port=8080
spring.jpa.hibernate.ddl_auto=update
logging.level.org.springframework.security=DEBUG
jwt.secret=mYS4cc0StR0ngJWTsEcrEtK3yThatIsAtLeast32Bytes
spring.datasource.username=root
spring.datasource.password=
spring.jackson.deserialization.fail-on-null-for-primitives=false
#normalize headers behind a proxy
server.forward-headers-strategy=framework
