spring.application.name=mysacco
server.port=9090
logging.level.org.springframework.security=DEBUG
jwt.secret=mYS4cc0StR0ngJWTsEcrEtK3yThatIsAtLeast32Bytes
spring.datasource.username=root
spring.datasource.password=
spring.jackson.deserialization.fail-on-null-for-primitives=false